name: notification_master
description: "A multi-platform Flutter notification plugin with custom channels, background polling, and foreground service support."
version: 0.0.5
homepage: "https://github.com/SwanFlutter/notification_master.git"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  plugin_platform_interface: ^2.1.8
  workmanager: ^0.9.0+3
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.notification_master
        pluginClass: NotificationMasterPlugin
      ios:
        pluginClass: NotificationMasterPlugin
      linux:
        pluginClass: NotificationMasterPlugin
      macos:
        pluginClass: NotificationMasterPlugin
      windows:
        pluginClass: NotificationMasterPluginCApi
      web:
        pluginClass: NotificationMasterWeb
        fileName: notification_master_web.dart
